steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/api:$SHORT_SHA', 'kod/.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/api:$SHORT_SHA']

# Deploy an image from Container Registry to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'api', '--image', 'eu.gcr.io/$PROJECT_ID]api:$SHORT_SHA', '--region', europe-west1, '--platform', 'managed', '--allow-unauthenticated']

images: ['eu.gcr.io/$PROJECT_ID/api:$SHORT_SHA']