steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/api:$SHORT_SHA', 'kod/.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/api:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'create', '--region', 'EUROPE-NORTH-1']

images: ['eu.gcr.io/$PROJECT_ID/api:$SHORT_SHA']