basePath: /api/v1
definitions:
  main.responseMessage:
    properties:
      message:
        example: Meaningful message
        type: string
      resourceId:
        type: integer
      status:
        type: integer
    type: object
  main.trackInfoModel:
    properties:
      country:
        example: Sweden
        type: string
      layout_image:
        items:
          type: integer
        type: array
      length:
        type: integer
      official_record:
        type: string
      trackname:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Used for GoFormululaUno.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GoFormulaUno
  version: "1.0"
paths:
  /tracks/:
    get:
      description: get track
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.trackInfoModel'
            type: array
        "404":
          description: Not Found
          schema:
            items:
              $ref: '#/definitions/main.responseMessage'
            type: array
      summary: Get track
swagger: "2.0"
